// <auto-generated />
using System;
using FitApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609134216_AddRefreshToken")]
    partial class AddRefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitApp.Domain.Entities.BodyMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BodyFatPercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("Hips")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Waist")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BodyMeasurements");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9eb50c5b-8614-4b2c-bc2f-4bcab75e9989"),
                            IsCustom = false,
                            MuscleGroup = "Klatka",
                            Name = "Wyciskanie sztangi leżąc"
                        },
                        new
                        {
                            Id = new Guid("d1200c1c-082a-45f2-b1c3-d16db2541031"),
                            IsCustom = false,
                            MuscleGroup = "Klatka",
                            Name = "Wyciskanie hantli na skosie"
                        },
                        new
                        {
                            Id = new Guid("b1150c95-cda4-493d-b637-48f51de164df"),
                            IsCustom = false,
                            MuscleGroup = "Klatka",
                            Name = "Rozpiętki na bramie"
                        },
                        new
                        {
                            Id = new Guid("75941a11-48c6-4853-8b94-b8b078cfdf9f"),
                            IsCustom = false,
                            MuscleGroup = "Plecy",
                            Name = "Martwy ciąg"
                        },
                        new
                        {
                            Id = new Guid("0755d1d9-54d5-48bb-82ac-8ad58029ba4c"),
                            IsCustom = false,
                            MuscleGroup = "Plecy",
                            Name = "Podciąganie na drążku"
                        },
                        new
                        {
                            Id = new Guid("9e74f916-fb5a-49f6-b02d-039f2d874208"),
                            IsCustom = false,
                            MuscleGroup = "Plecy",
                            Name = "Wiosłowanie sztangą"
                        },
                        new
                        {
                            Id = new Guid("a21bbae5-9d73-48d5-8b72-98a555183993"),
                            IsCustom = false,
                            MuscleGroup = "Nogi",
                            Name = "Przysiad ze sztangą"
                        },
                        new
                        {
                            Id = new Guid("900179c0-e035-41c8-8cff-41047d53f728"),
                            IsCustom = false,
                            MuscleGroup = "Nogi",
                            Name = "Wykroki z hantlami"
                        },
                        new
                        {
                            Id = new Guid("36cf2c4b-31ae-4ca8-8578-fa485486b3ec"),
                            IsCustom = false,
                            MuscleGroup = "Nogi",
                            Name = "Prostowanie nóg na maszynie"
                        },
                        new
                        {
                            Id = new Guid("0b529b22-6546-4522-8c7c-dbda75485c28"),
                            IsCustom = false,
                            MuscleGroup = "Barki",
                            Name = "Wyciskanie żołnierskie (OHP)"
                        },
                        new
                        {
                            Id = new Guid("5d808eac-6a21-4a6a-b85c-3a97d0d38faf"),
                            IsCustom = false,
                            MuscleGroup = "Barki",
                            Name = "Wznosy bokiem"
                        },
                        new
                        {
                            Id = new Guid("52ed863f-f00c-4de8-8a27-035cf89faeea"),
                            IsCustom = false,
                            MuscleGroup = "Ramiona",
                            Name = "Uginanie ramion ze sztangą"
                        },
                        new
                        {
                            Id = new Guid("9753b98f-b41a-4411-bb8b-87af642b92e8"),
                            IsCustom = false,
                            MuscleGroup = "Ramiona",
                            Name = "Prostowanie ramion na wyciągu"
                        },
                        new
                        {
                            Id = new Guid("bb543db9-e090-4d10-ba5c-f09c5d404b8c"),
                            IsCustom = false,
                            MuscleGroup = "Brzuch",
                            Name = "Plank"
                        },
                        new
                        {
                            Id = new Guid("7eee9d25-94a3-4c08-b47d-136aca842828"),
                            IsCustom = false,
                            MuscleGroup = "Brzuch",
                            Name = "Unoszenie nóg"
                        },
                        new
                        {
                            Id = new Guid("3eb0f25b-2f7b-457d-a2c8-3e9824b75560"),
                            IsCustom = false,
                            MuscleGroup = "Cardio",
                            Name = "Bieg / cardio"
                        });
                });

            modelBuilder.Entity("FitApp.Domain.Entities.FoodProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CalciumPer100g")
                        .HasColumnType("numeric");

                    b.Property<int>("CaloriesPer100g")
                        .HasColumnType("integer");

                    b.Property<decimal>("CarbsPer100g")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FatsPer100g")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FiberPer100g")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IronPer100g")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProteinPer100g")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SaturatedFatPer100g")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SodiumPer100g")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SugarsPer100g")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("FoodProducts");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.MealLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("TotalCalcium")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCarbs")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalFats")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalFiber")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIron")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalProtein")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalSaturatedFat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalSodium")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalSugars")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealLogs");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.MealLogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Grams")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MealLogId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FoodProductId");

                    b.HasIndex("MealLogId");

                    b.ToTable("MealLogItem");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.MealPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<decimal>("Carbs")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Fats")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("FoodProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Grams")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Proteins")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FoodProductId");

                    b.HasIndex("MealPlanId");

                    b.ToTable("MealPlanItems");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.SetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("SetEntries");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActivityMultiplier")
                        .HasColumnType("numeric");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("LastStreakUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("TargetWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.WaterLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmountMl")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WaterLogs");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.BodyMeasurement", b =>
                {
                    b.HasOne("FitApp.Domain.Entities.User", null)
                        .WithMany("BodyMeasurements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitApp.Domain.Entities.MealLog", b =>
                {
                    b.HasOne("FitApp.Domain.Entities.User", null)
                        .WithMany("MealLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitApp.Domain.Entities.MealLogItem", b =>
                {
                    b.HasOne("FitApp.Domain.Entities.FoodProduct", "FoodProduct")
                        .WithMany()
                        .HasForeignKey("FoodProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitApp.Domain.Entities.MealLog", null)
                        .WithMany("Items")
                        .HasForeignKey("MealLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodProduct");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.MealPlan", b =>
                {
                    b.HasOne("FitApp.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.MealPlanItem", b =>
                {
                    b.HasOne("FitApp.Domain.Entities.FoodProduct", "FoodProduct")
                        .WithMany()
                        .HasForeignKey("FoodProductId");

                    b.HasOne("FitApp.Domain.Entities.MealPlan", "MealPlan")
                        .WithMany("Items")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodProduct");

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.SetEntry", b =>
                {
                    b.HasOne("FitApp.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitApp.Domain.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.MealLog", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.MealPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.User", b =>
                {
                    b.Navigation("BodyMeasurements");

                    b.Navigation("MealLogs");
                });

            modelBuilder.Entity("FitApp.Domain.Entities.WorkoutSession", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
